config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :askings
  get 'static_pages/home'
  get 'static_pages/results'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/random', to: 'askings#random'
  get '/results', to: 'askings#results'
  get '/reset', to: 'askings#reset'
  
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asking.rb
class Asking < ApplicationRecord
    
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  skip_before_action :verify_authenticity_token
  
  
end

app/controllers/askings_controller.rb
class AskingsController < ApplicationController
  before_action :set_asking, only: %i[ show edit update destroy ]

  # GET /askings or /askings.json
  def index
    @askings = Asking.all
  end

  # GET /askings/1 or /askings/1.json
  def show
  end

  # GET /askings/new
  def new
    @asking = Asking.new
  end

  # GET /askings/1/edit
  def edit
  end

  # POST /askings or /askings.json
  def create
    @asking = Asking.new(asking_params)

    respond_to do |format|
      if @asking.save
        format.html { redirect_to @asking, notice: "Asking was successfully created." }
        format.json { render :show, status: :created, location: @asking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @asking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /askings/1 or /askings/1.json
  def update
    if Asking.sum("answered") <4
      respond_to do |format|
        if @asking.update(asking_params)
          format.html { redirect_to random_url}
          format.json { render :show, status: :ok, location: @asking }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @asking.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @asking.update(asking_params)
          format.html { redirect_to results_url}
          format.json { render :show, status: :ok, location: @asking }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @asking.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /askings/1 or /askings/1.json
  def destroy
    @asking.destroy
    respond_to do |format|
      format.html { redirect_to askings_url, notice: "Asking was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def random
    offset = rand(10)
    @question = Asking.offset(offset).first
    if @question.answered == 1
      redirect_to random_url
    else
    @question.answered = 1
    @question.save
    redirect_to @question
    end
  end
  
  def results
    Asking.where("selectedanswer != 'nil'").each do |q|
      if q.answer_a_correct == "true"
        if q.answer_a == q.selectedanswer
          q.score = 1
        end
      end
      if q.answer_b_correct == "true"
        if q.answer_b == q.selectedanswer
          q.score = 1
        end
      end
      if q.answer_c_correct == "true"
        if q.answer_c == q.selectedanswer
          q.score = 1
        end
      end
      if q.answer_d_correct == "true"
        if q.answer_d == q.selectedanswer
          q.score = 1
        end
      end
      if q.answer_e_correct == "true"
        if q.answer_e === q.selectedanswer
          q.score = 1
        end
      end
      if q.answer_f_correct == "true"
        if q.answer_f == q.selectedanswer
          q.score = 1
        end
      end
      q.save
    end
    x = Asking.sum("score")
    if x > Asking.first.high_score
      Asking.all.each do |q|
        q.high_score = x
        q.save
     end
    end
   Record.create(numberCorrect: x, attemptsago: 0)
  end
  
  def reset
    Asking.all.each do |q|
      q.answered = 0
      q.selectedanswer = nil
      q.score = 0
      q.save
    end
    Record.all.each do |r|
      r.attemptsago = r.attemptsago+1
      r.save
    end
    redirect_to random_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asking
      @asking = Asking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def asking_params
      params.require(:asking).permit(:question, :description, :answers, :multiple_correct_answers, :correct_answers, :selectedanswer)
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[ show edit update destroy ]

  # GET /records or /records.json
  def index
    @records = Record.all
  end

  # GET /records/1 or /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records or /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: "Record was successfully created." }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: "Record was successfully updated." }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: "Record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def record_params
      params.require(:record).permit(:numberCorrect, :attemptsAgo)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/askings_helper.rb
module AskingsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/askings/_form.html.erb
<%= form_for(asking) do |f| %>
  <% if asking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asking.errors.count, "error") %> prohibited this asking from being saved:</h2>

      <ul>
      <% asking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %>
    <%= f.text_field :question %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :multiple_correct_answers %>
    <%= f.text_field :multiple_correct_answers %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/askings/edit.html.erb
<h1>Editing Asking</h1>

<%= render 'form', asking: @asking %>

<%= link_to 'Show', @asking %> |
<%= link_to 'Back', askings_path %>

app/views/askings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Askings</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Description</th>
      <th>Multiple correct answers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @askings.each do |asking| %>
      <tr>
        <td><%= asking.question %></td>
        <td><%= asking.description %></td>
        <td><%= asking.multiple_correct_answers %></td>
        <td><%= link_to 'Show', asking %></td>
        <td><%= link_to 'Edit', edit_asking_path(asking) %></td>
        <td><%= link_to 'Destroy', asking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asking', new_asking_path %>

app/views/askings/new.html.erb
<h1>New Asking</h1>

<%= render 'form', asking: @asking %>

<%= link_to 'Back', askings_path %>

app/views/askings/results.html.erb
<%provide(:title,"Results")%>
<div class="container">
  <div class="center jumbotron">
    <h1>You Scored:</h1>
    <h2><%=@score = Asking.sum("score")%></h2>
    <h2>out of 4</h2>
    <% x = Record.where("attemptsago > '0'")%>
    <% x.where("attemptsago < '6'").each do |q|%>
    <h3><%=q.attemptsago%> attempt(s) ago, you scored <%=q.numberCorrect%></h3>
    <%end%>
    <p><%= link_to "Lets go!", reset_url, class: "btnbtn-lg btn-primary" %></p>
  </div>

app/views/askings/shared/_error_messages.html.erb
<% if @asking.errors.any?%>
    <div id="error_messages">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@asking.errors.count, "error") %>.
        </div>
        <ul>
            <% @asking.errors.full_messages.each do |message| %>
            <li><%= message%></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/askings/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
    <%=@asking.question%>
</h2>
<%= form_for(@asking) do |f| %>
  
<div class="form_row">
    <%if @asking.answer_a != nil%>
    <%= f.radio_button :selectedanswer, @asking.answer_a, checked: true %>
    <%= f.label :selectedanswer, @asking.answer_a %>
    <%end%>
    
    <%if @asking.answer_b != nil%>
    <%= f.radio_button :selectedanswer, @asking.answer_b %>
    <%= f.label :selectedanswer, @asking.answer_b %>
    <%end%>
    
    
    <%if @asking.answer_c != nil%>
    <%= f.radio_button :selectedanswer, @asking.answer_c %>
    <%= f.label :selectedanswer, @asking.answer_c %>
    <%end%>
    
    
    <%if @asking.answer_d != nil%>
    <%= f.radio_button :selectedanswer, @asking.answer_d %>
    <%= f.label :selectedanswer, @asking.answer_d %>
    <%end%>
    
    
    <%if @asking.answer_e != nil%>
    <%= f.radio_button :selectedanswer, @asking.answer_e %>
    <%= f.label :selectedanswer, @asking.answer_e %>
    <%end%>
    
    <%if @asking.answer_f != nil%>
    <%= f.radio_button :selectedanswer, @asking.answer_f %>
    <%= f.label :selectedanswer, @asking.answer_f %>
    <%end%>
</div>



<%if Asking.sum("answered")>3%>
    <input type="submit" value="Submit">
<%else%>
    <div class="actions">
    <input type="submit" value="Continue">
    </div>
<%end%>

<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        <%i = Asking.first.high_score%>
        <%="High Score:" +i.to_s%>
    </small>
    <nav>
        <ul>
            <a href="https://www.facebook.com/">FaceBook</a>
            <a href="https://au.linkedin.com/">LinkedIn</a>
            <a href="https://twitter.com/">Twitter</a>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="row">
        <div class="column"><h2>Quiz+</h2></div>
        <div class="column"><h2>William Furler</h2></div>
        <div class="column"><h2>s3848792@student.rmit.edu.au</h2></div>
    </div>
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | Quiz+ </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_for(record) do |f| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numberCorrect %>
    <%= f.number_field :numberCorrect %>
  </div>

  <div class="field">
    <%= f.label :attemptsAgo %>
    <%= f.number_field :attemptsAgo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Records</h1>

<table>
  <thead>
    <tr>
      <th>Numbercorrect</th>
      <th>Attemptsago</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.numberCorrect %></td>
        <td><%= record.attemptsAgo %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numbercorrect:</strong>
  <%= @record.numberCorrect %>
</p>

<p>
  <strong>Attemptsago:</strong>
  <%= @record.attemptsAgo %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/static_pages/home.html.erb
<%provide(:title,"Home")%>
<div class="container">
  <div class="center jumbotron">
    <h1>Take the Quiz</h1>
        <p><%= link_to "Lets go!", random_url, class: "btnbtn-lg btn-primary" %></p>
  </div>